-- Base para soporte multi-sucursal (preparacion)

CREATE TABLE IF NOT EXISTS branches (
  id SERIAL PRIMARY KEY,
  code VARCHAR(30) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO branches (id, code, name, active)
VALUES (1, 'CENTRAL', 'Sucursal Central', true)
ON CONFLICT (id) DO NOTHING;

SELECT setval(
  pg_get_serial_sequence('branches', 'id'),
  GREATEST((SELECT COALESCE(MAX(id), 1) FROM branches), 1),
  true
);

ALTER TABLE users
ADD COLUMN IF NOT EXISTS branch_id INTEGER;

UPDATE users SET branch_id = 1 WHERE branch_id IS NULL;

ALTER TABLE users
ALTER COLUMN branch_id SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'users_branch_id_fkey'
      AND table_name = 'users'
  ) THEN
    ALTER TABLE users
    ADD CONSTRAINT users_branch_id_fkey
    FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE RESTRICT;
  END IF;
END $$;

ALTER TABLE categories DROP CONSTRAINT IF EXISTS categories_name_key;
CREATE UNIQUE INDEX IF NOT EXISTS idx_categories_branch_name_unique
ON categories(branch_id, name);

ALTER TABLE categories
ADD COLUMN IF NOT EXISTS branch_id INTEGER;

UPDATE categories SET branch_id = 1 WHERE branch_id IS NULL;
ALTER TABLE categories ALTER COLUMN branch_id SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'categories_branch_id_fkey'
      AND table_name = 'categories'
  ) THEN
    ALTER TABLE categories
    ADD CONSTRAINT categories_branch_id_fkey
    FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE RESTRICT;
  END IF;
END $$;

ALTER TABLE products
ADD COLUMN IF NOT EXISTS branch_id INTEGER;

UPDATE products SET branch_id = 1 WHERE branch_id IS NULL;
ALTER TABLE products ALTER COLUMN branch_id SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'products_branch_id_fkey'
      AND table_name = 'products'
  ) THEN
    ALTER TABLE products
    ADD CONSTRAINT products_branch_id_fkey
    FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE RESTRICT;
  END IF;
END $$;

ALTER TABLE cash_sessions
ADD COLUMN IF NOT EXISTS branch_id INTEGER;

UPDATE cash_sessions SET branch_id = 1 WHERE branch_id IS NULL;
ALTER TABLE cash_sessions ALTER COLUMN branch_id SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'cash_sessions_branch_id_fkey'
      AND table_name = 'cash_sessions'
  ) THEN
    ALTER TABLE cash_sessions
    ADD CONSTRAINT cash_sessions_branch_id_fkey
    FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE RESTRICT;
  END IF;
END $$;

ALTER TABLE sales
ADD COLUMN IF NOT EXISTS branch_id INTEGER;

UPDATE sales SET branch_id = 1 WHERE branch_id IS NULL;
ALTER TABLE sales ALTER COLUMN branch_id SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'sales_branch_id_fkey'
      AND table_name = 'sales'
  ) THEN
    ALTER TABLE sales
    ADD CONSTRAINT sales_branch_id_fkey
    FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE RESTRICT;
  END IF;
END $$;

ALTER TABLE store_settings
ADD COLUMN IF NOT EXISTS branch_id INTEGER;

UPDATE store_settings SET branch_id = 1 WHERE branch_id IS NULL;
ALTER TABLE store_settings ALTER COLUMN branch_id SET NOT NULL;

ALTER TABLE store_settings DROP CONSTRAINT IF EXISTS store_settings_id_check;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'store_settings_branch_id_fkey'
      AND table_name = 'store_settings'
  ) THEN
    ALTER TABLE store_settings
    ADD CONSTRAINT store_settings_branch_id_fkey
    FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE RESTRICT;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_store_settings_branch_unique
ON store_settings(branch_id);

DO $$
BEGIN
  BEGIN
    ALTER TABLE store_settings
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN feature_not_supported THEN NULL;
  END;
END $$;

ALTER TABLE sale_returns
ADD COLUMN IF NOT EXISTS branch_id INTEGER;

UPDATE sale_returns SET branch_id = 1 WHERE branch_id IS NULL;
ALTER TABLE sale_returns ALTER COLUMN branch_id SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE constraint_name = 'sale_returns_branch_id_fkey'
      AND table_name = 'sale_returns'
  ) THEN
    ALTER TABLE sale_returns
    ADD CONSTRAINT sale_returns_branch_id_fkey
    FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE RESTRICT;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_users_branch_id ON users(branch_id);
CREATE INDEX IF NOT EXISTS idx_products_branch_id ON products(branch_id);
CREATE INDEX IF NOT EXISTS idx_categories_branch_id ON categories(branch_id);
CREATE INDEX IF NOT EXISTS idx_sales_branch_id ON sales(branch_id);
CREATE INDEX IF NOT EXISTS idx_cash_sessions_branch_id ON cash_sessions(branch_id);
CREATE INDEX IF NOT EXISTS idx_sale_returns_branch_id ON sale_returns(branch_id);
